def getError(error_code, error_message):                      
    raise Exception(f"(error code {error_code}: {error_message}")

